---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: markdown-linting-pipeline
spec:
  workspaces:
  - name: shared-workspace
  tasks:
  - name: clone-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
      - name: output
        workspace: shared-workspace
    params:
    - name: url
      value: https://github.com/upslopeio/lint-markdown-files.git
    - name: deleteExisting
      value: "true"
  - name: lint-file
    taskRef:
      name: markdown-lint
      kind: Task
    runAfter:
        - clone-repository
    workspaces:
      - name: shared-workspace
        workspace: shared-workspace
    params:
      - name: args
        value: ["."]